{"version":3,"sources":["../../src/errors/internal-error.js"],"names":["app","info","err","log","error","Promise","reject","message"],"mappings":";;;;;;;;AAAA;;AACA;;;;;;kBAEe,UAACA,GAAD,EAAoB;AAAA,MAAdC,IAAc,uEAAP,EAAO;;AACjC,SAAQC,GAAD,IAAS;AACdF,QAAIG,GAAJ,CAAQC,KAAR,CAAcF,GAAd,EAAmBD,IAAnB;AACA,WAAOI,QAAQC,MAAR,CAAe,gCAAQC,wCAAR,IAA0CN,IAA1C,EAAf,CAAP;AACD,GAHD;AAID,C","file":"internal-error.js","sourcesContent":["import { ERROR_INTERNAL_ERROR } from './../constants';\nimport error from './error';\n\nexport default (app, info = {}) => {\n  return (err) => {\n    app.log.error(err, info);\n    return Promise.reject(error({ message: ERROR_INTERNAL_ERROR, ...info }));\n  };\n};"]}